CREATE TABLE IF NOT EXISTS PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);